from __future__ import annotations


BRONZE_HISTORY_TABLE = "MTA_BRONZE_LOAD_HISTORY"
SILVER_HISTORY_TABLE = "MTA_SILVER_LOAD_HISTORY"
GOLD_HISTORY_TABLE = "MTA_GOLD_LOAD_HISTORY"

SILVER_TABLES = [
    "MTA_FEED_SNAPSHOTS_SILVER",
    "MTA_TRIP_UPDATES_SILVER",
    "MTA_STOP_TIME_UPDATES_SILVER",
    "MTA_VEHICLE_POSITIONS_SILVER",
    "MTA_ALERTS_SILVER",
]

GOLD_TABLES = [
    "MTA_ARRIVAL_INFERENCE_GOLD",
    "MTA_ROUTE_HEADWAYS_GOLD",
    "MTA_ROUTE_SNAPSHOT_SUMMARY_GOLD",
    "MTA_ALERT_ACTIVITY_GOLD",
]


CREATE_TABLE_STATEMENTS = {
    BRONZE_HISTORY_TABLE: """
        CREATE TABLE IF NOT EXISTS MTA_BRONZE_LOAD_HISTORY (
            OBJECT_KEY STRING,
            INGESTION_ID STRING,
            DAG_RUN_ID STRING,
            DATA_TYPE STRING,
            FEED_NAME STRING,
            SOURCE_URL STRING,
            INGESTED_AT TIMESTAMP_TZ,
            LOADED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
            STATUS STRING,
            ROW_COUNT NUMBER,
            TABLE_COUNTS_JSON STRING,
            ERROR_MESSAGE STRING
        )
    """,
    SILVER_HISTORY_TABLE: """
        CREATE TABLE IF NOT EXISTS MTA_SILVER_LOAD_HISTORY (
            OBJECT_KEY STRING,
            INGESTION_ID STRING,
            DAG_RUN_ID STRING,
            DATA_TYPE STRING,
            FEED_NAME STRING,
            SOURCE_URL STRING,
            INGESTED_AT TIMESTAMP_TZ,
            LOADED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
            STATUS STRING,
            ROW_COUNT NUMBER,
            TABLE_COUNTS_JSON STRING,
            ERROR_MESSAGE STRING
        )
    """,
    GOLD_HISTORY_TABLE: """
        CREATE TABLE IF NOT EXISTS MTA_GOLD_LOAD_HISTORY (
            OBJECT_KEY STRING,
            INGESTION_ID STRING,
            DAG_RUN_ID STRING,
            DATA_TYPE STRING,
            FEED_NAME STRING,
            SOURCE_URL STRING,
            INGESTED_AT TIMESTAMP_TZ,
            LOADED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
            STATUS STRING,
            ROW_COUNT NUMBER,
            TABLE_COUNTS_JSON STRING,
            ERROR_MESSAGE STRING
        )
    """,
    "MTA_FEED_SNAPSHOTS_SILVER": """
        CREATE TABLE IF NOT EXISTS MTA_FEED_SNAPSHOTS_SILVER (
            FEED_SNAPSHOT_KEY STRING,
            OBJECT_KEY STRING,
            INGESTION_ID STRING,
            DAG_RUN_ID STRING,
            FEED_NAME STRING,
            SOURCE_URL STRING,
            DATA_TYPE STRING,
            INGESTED_AT TIMESTAMP_TZ,
            FEED_TIMESTAMP TIMESTAMP_TZ,
            ENTITY_COUNT NUMBER,
            TRIP_UPDATE_COUNT NUMBER,
            VEHICLE_POSITION_COUNT NUMBER,
            ALERT_COUNT NUMBER,
            ROUTE_IDS_JSON STRING,
            FEED_HEADER_JSON STRING,
            NYCT_FEED_HEADER_JSON STRING,
            RAW_PAYLOAD_JSON STRING,
            LOADED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
        )
    """,
    "MTA_TRIP_UPDATES_SILVER": """
        CREATE TABLE IF NOT EXISTS MTA_TRIP_UPDATES_SILVER (
            TRIP_OBSERVATION_KEY STRING,
            TRIP_STABLE_KEY STRING,
            OBJECT_KEY STRING,
            INGESTION_ID STRING,
            DAG_RUN_ID STRING,
            FEED_NAME STRING,
            SOURCE_URL STRING,
            INGESTED_AT TIMESTAMP_TZ,
            FEED_TIMESTAMP TIMESTAMP_TZ,
            ENTITY_ID STRING,
            TRIP_ID STRING,
            ROUTE_ID STRING,
            START_DATE STRING,
            START_TIME STRING,
            TRAIN_ID STRING,
            DIRECTION STRING,
            IS_ASSIGNED BOOLEAN,
            SCHEDULE_RELATIONSHIP STRING,
            TRIP_UPDATE_TIMESTAMP TIMESTAMP_TZ,
            STOP_TIME_UPDATE_COUNT NUMBER,
            NYCT_TRIP_DESCRIPTOR_JSON STRING,
            RAW_TRIP_UPDATE_JSON STRING,
            LOADED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
        )
    """,
    "MTA_STOP_TIME_UPDATES_SILVER": """
        CREATE TABLE IF NOT EXISTS MTA_STOP_TIME_UPDATES_SILVER (
            STOP_TIME_OBSERVATION_KEY STRING,
            TRIP_STOP_STABLE_KEY STRING,
            TRIP_STABLE_KEY STRING,
            OBJECT_KEY STRING,
            INGESTION_ID STRING,
            DAG_RUN_ID STRING,
            FEED_NAME STRING,
            SOURCE_URL STRING,
            INGESTED_AT TIMESTAMP_TZ,
            FEED_TIMESTAMP TIMESTAMP_TZ,
            ENTITY_ID STRING,
            TRIP_ID STRING,
            ROUTE_ID STRING,
            START_DATE STRING,
            START_TIME STRING,
            TRAIN_ID STRING,
            DIRECTION STRING,
            STOP_SEQUENCE_INDEX NUMBER,
            STOP_ID STRING,
            ARRIVAL_TIME TIMESTAMP_TZ,
            DEPARTURE_TIME TIMESTAMP_TZ,
            ARRIVAL_DELAY_SECONDS NUMBER,
            DEPARTURE_DELAY_SECONDS NUMBER,
            SCHEDULE_RELATIONSHIP STRING,
            NYCT_STOP_TIME_UPDATE_JSON STRING,
            RAW_STOP_TIME_UPDATE_JSON STRING,
            LOADED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
        )
    """,
    "MTA_VEHICLE_POSITIONS_SILVER": """
        CREATE TABLE IF NOT EXISTS MTA_VEHICLE_POSITIONS_SILVER (
            VEHICLE_OBSERVATION_KEY STRING,
            TRIP_STABLE_KEY STRING,
            OBJECT_KEY STRING,
            INGESTION_ID STRING,
            DAG_RUN_ID STRING,
            FEED_NAME STRING,
            SOURCE_URL STRING,
            INGESTED_AT TIMESTAMP_TZ,
            FEED_TIMESTAMP TIMESTAMP_TZ,
            ENTITY_ID STRING,
            VEHICLE_ID STRING,
            TRIP_ID STRING,
            ROUTE_ID STRING,
            START_DATE STRING,
            START_TIME STRING,
            TRAIN_ID STRING,
            DIRECTION STRING,
            STOP_ID STRING,
            CURRENT_STOP_SEQUENCE NUMBER,
            CURRENT_STATUS STRING,
            VEHICLE_TIMESTAMP TIMESTAMP_TZ,
            LATITUDE FLOAT,
            LONGITUDE FLOAT,
            BEARING FLOAT,
            RAW_VEHICLE_JSON STRING,
            LOADED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
        )
    """,
    "MTA_ALERTS_SILVER": """
        CREATE TABLE IF NOT EXISTS MTA_ALERTS_SILVER (
            ALERT_OBSERVATION_KEY STRING,
            OBJECT_KEY STRING,
            INGESTION_ID STRING,
            DAG_RUN_ID STRING,
            FEED_NAME STRING,
            SOURCE_URL STRING,
            INGESTED_AT TIMESTAMP_TZ,
            FEED_TIMESTAMP TIMESTAMP_TZ,
            ENTITY_ID STRING,
            ROUTE_ID STRING,
            STOP_ID STRING,
            ALERT_CAUSE STRING,
            ALERT_EFFECT STRING,
            ACTIVE_PERIOD_START TIMESTAMP_TZ,
            ACTIVE_PERIOD_END TIMESTAMP_TZ,
            INFORMED_ENTITY_COUNT NUMBER,
            HEADER_TEXT STRING,
            DESCRIPTION_TEXT STRING,
            INFORMED_ENTITIES_JSON STRING,
            RAW_ALERT_JSON STRING,
            LOADED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
        )
    """,
    "MTA_ARRIVAL_INFERENCE_GOLD": """
        CREATE TABLE IF NOT EXISTS MTA_ARRIVAL_INFERENCE_GOLD (
            ARRIVAL_INFERENCE_KEY STRING,
            ROUTE_ID STRING,
            TRIP_ID STRING,
            START_DATE STRING,
            START_TIME STRING,
            TRAIN_ID STRING,
            DIRECTION STRING,
            STOP_ID STRING,
            FIRST_SEEN_INGESTED_AT TIMESTAMP_TZ,
            LAST_SEEN_INGESTED_AT TIMESTAMP_TZ,
            FIRST_PREDICTED_ARRIVAL_TS TIMESTAMP_TZ,
            LAST_PREDICTED_ARRIVAL_TS TIMESTAMP_TZ,
            FIRST_PREDICTED_DEPARTURE_TS TIMESTAMP_TZ,
            LAST_PREDICTED_DEPARTURE_TS TIMESTAMP_TZ,
            POLL_COUNT NUMBER,
            PREDICTION_DRIFT_SECONDS FLOAT,
            PREDICTION_VARIANCE_SECONDS FLOAT,
            OBSERVED_SPAN_SECONDS FLOAT,
            INFERRED_COMPLETION_PROXY_TS TIMESTAMP_TZ,
            LAST_SOURCE_OBJECT_KEY STRING,
            UPDATED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
        )
    """,
    "MTA_ROUTE_HEADWAYS_GOLD": """
        CREATE TABLE IF NOT EXISTS MTA_ROUTE_HEADWAYS_GOLD (
            HEADWAY_WINDOW_KEY STRING,
            ROUTE_ID STRING,
            DIRECTION STRING,
            STOP_ID STRING,
            WINDOW_START TIMESTAMP_TZ,
            WINDOW_END TIMESTAMP_TZ,
            TRIP_COUNT NUMBER,
            AVG_HEADWAY_SECONDS FLOAT,
            MIN_HEADWAY_SECONDS FLOAT,
            MAX_HEADWAY_SECONDS FLOAT,
            UPDATED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
        )
    """,
    "MTA_ROUTE_SNAPSHOT_SUMMARY_GOLD": """
        CREATE TABLE IF NOT EXISTS MTA_ROUTE_SNAPSHOT_SUMMARY_GOLD (
            ROUTE_SNAPSHOT_KEY STRING,
            OBJECT_KEY STRING,
            INGESTION_ID STRING,
            FEED_NAME STRING,
            ROUTE_ID STRING,
            SNAPSHOT_TS TIMESTAMP_TZ,
            TRIP_UPDATE_COUNT NUMBER,
            STOP_TIME_UPDATE_COUNT NUMBER,
            VEHICLE_POSITION_COUNT NUMBER,
            ALERT_COUNT NUMBER,
            UPDATED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
        )
    """,
    "MTA_ALERT_ACTIVITY_GOLD": """
        CREATE TABLE IF NOT EXISTS MTA_ALERT_ACTIVITY_GOLD (
            ALERT_ACTIVITY_KEY STRING,
            ROUTE_ID STRING,
            WINDOW_START TIMESTAMP_TZ,
            WINDOW_END TIMESTAMP_TZ,
            ALERT_SNAPSHOT_COUNT NUMBER,
            DISTINCT_ALERT_ENTITY_COUNT NUMBER,
            MAX_INFORMED_ENTITY_COUNT NUMBER,
            ACTIVE_ALERT_COUNT NUMBER,
            UPDATED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
        )
    """,
}
