CREATE TABLE IF NOT EXISTS RAW_MTA_SUBWAY_FEED_RUNS (
    INGESTION_ID STRING,
    DAG_RUN_ID STRING,
    FEED_NAME STRING,
    SOURCE_URL STRING,
    REQUESTED_AT TIMESTAMP_TZ,
    FEED_TIMESTAMP TIMESTAMP_TZ,
    ENTITY_COUNT NUMBER,
    HTTP_STATUS NUMBER,
    SUCCESS BOOLEAN,
    ERROR_MESSAGE STRING,
    INSERTED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS RAW_MTA_SUBWAY_ENTITIES (
    INGESTION_ID STRING,
    DAG_RUN_ID STRING,
    FEED_NAME STRING,
    SOURCE_URL STRING,
    REQUESTED_AT TIMESTAMP_TZ,
    FEED_TIMESTAMP TIMESTAMP_TZ,
    ENTITY_ID STRING,
    ENTITY_TYPE STRING,
    ROUTE_ID STRING,
    TRIP_ID STRING,
    START_DATE STRING,
    VEHICLE_ID STRING,
    STOP_ID STRING,
    CURRENT_STOP_SEQUENCE NUMBER,
    CURRENT_STATUS STRING,
    RAW_ENTITY_JSON STRING,
    INSERTED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS RAW_MTA_SUBWAY_STOP_TIME_UPDATES (
    INGESTION_ID STRING,
    DAG_RUN_ID STRING,
    FEED_NAME STRING,
    SOURCE_URL STRING,
    REQUESTED_AT TIMESTAMP_TZ,
    FEED_TIMESTAMP TIMESTAMP_TZ,
    ENTITY_ID STRING,
    TRIP_ID STRING,
    ROUTE_ID STRING,
    STOP_SEQUENCE_INDEX NUMBER,
    STOP_ID STRING,
    ARRIVAL_TIME TIMESTAMP_TZ,
    DEPARTURE_TIME TIMESTAMP_TZ,
    SCHEDULE_RELATIONSHIP STRING,
    RAW_STOP_TIME_JSON STRING,
    INSERTED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
);